export const DRUM_MAP = new Map<string, string>([
  ['B1', 'BD-'],
  ['C2', 'BD-'],
  ['D2', 'SD-'],
  ['E2', 'SD-'],
  ['F2', 'LT-'],
  ['F#2', 'CHH'],
  ['G2', 'RCY'],
  ['G#2', 'CHH'],
  ['A2', 'LT-'],
  ['A#2', 'OHH'],
  ['B2', 'MT-'],
  ['C3', 'MT-'],
  ['C#3', 'CYM'],
  ['D3', 'HT-'],
  ['D#3', 'RCY'],
  ['E3', 'CYM'],
  ['F3', 'RCY'],
  ['G3', 'CYM'],
  ['A3', 'CYM'],
  ['B3', 'RCY']
])
