name: Code Push Checks
run-name: ${{ github.event_name }} from ${{ github.actor }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-checks:
    name: 'Run Checks'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Linting
        run: yarn lint
      - name: Run Tests
        run: yarn test
      - name: Test Able To Build
        run: yarn build
      - name: Save Allure Report As Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report-${{ matrix.node-version }}
          path: allure-results
          retention-days: 1
  publish-check-results:
    name: 'Publish Check Results'
    runs-on: ubuntu-latest
    needs: run-checks
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download artifacts from Node 16 build
        uses: actions/download-artifact@v2
        with:
            name: allure-report-16.x
            path: allure-results
      - name: Download artifacts from Node 18 build
        uses: actions/download-artifact@v2
        with:
          name: allure-report-18.x
          path: allure-results
      - name: Download artifacts from Node 19 build
        uses: actions/download-artifact@v2
        with:
          name: allure-report-19.x
          path: allure-results
      - name: Create Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy Allure Report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
      - name: Add Allure Report Link to Checks Page
        uses: hkusu/status-create-action@v1
        with:
          sha: ${{ github.sha }}
          state: success
          target-url: https://colinfwren.github.io/midi-to-lsdj/${{ github.run_number }}
          context: 'Test Report'
